/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 robotic_eye.glb --transform 
Files: robotic_eye.glb [1.95MB] > /Users/jini.choi/Documents/jini/particle.jsx/public/models/particles/robotic_eye-transformed.glb [210.26KB] (89%)
Author: Aleksei Rozumnyi (https://sketchfab.com/Aleksei.Rozumnyi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robotic-eye-7b7ecc70526a4261a705f64655c13aa5
Title: Robotic Eye
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RoboticEye(props) {
  const { nodes, materials } = useGLTF(
    "./models/particles/robotic_eye-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Eyeball_Segment_Low_Poly_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-1.633, 0.001, -0.031]}
        scale={0.056}
      />
      <mesh
        geometry={nodes.Battery_0.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.003, 0.005, 0.08]}
        rotation={[1.563, -1.047, -3.079]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Light_Low_Poly_0.geometry}
        material={materials.Light}
        rotation={[-1.633, 0.001, -0.031]}
        scale={0.056}
      />
    </group>
  );
}

useGLTF.preload("./models/particles/robotic_eye-transformed.glb");
